<img src = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY1oshzQDwxkk6yLUIN8qMDUeH3eqofFzTnw1FXg1_RS3zyo6t">
<font color = "red" size = 8 >Random Forest</font><br>
<font color = "red" size = 4 >Regression</font>

<h1> You can download the dataset for this analysis from the link below</h1>
<a href="https://drive.google.com/file/d/1XeGMUcHrupVwSD-L2afuFTzEoW2zwZ0y/view?usp=sharing"><button type="button" class="btn btn-warning">Download Dataset here</button></a>


In [2]:
import pandas as pd  
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

os.chdir("c://users//gilgamesh//downloads")
dataset = pd.read_csv('petrol_consumption.csv')

In [3]:
dataset.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [4]:
#split the data for the training
X = dataset.iloc[:, 0:4].values  
y = dataset.iloc[:, 4].values 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)# splits the data into training and testing sets

In [5]:
#The data needs to be scaled for better model performance
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test) 

In [6]:
#Train the model using scikit -learn
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)  
regressor.fit(X_train, y_train)  
y_pred = regressor.predict(X_test)  

In [7]:
y_pred #predicted values

array([574.1 , 514.6 , 604.8 , 589.75, 625.55, 592.5 , 594.9 , 573.3 ,
       468.55, 536.8 ])

In [8]:
y_test # actual Values

array([534, 410, 577, 571, 577, 704, 487, 587, 467, 580], dtype=int64)

In [9]:
#Evaluating the model
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))  

print("With 20 trees, the root mean squared error is 64.93 which is greater than 10 percent of the average petrol consumption i.e. 576.77. This may indicate, among other things, that we have not used enough estimators (trees).")

Mean Absolute Error: 51.76500000000001
Mean Squared Error: 4216.166749999999
Root Mean Squared Error: 64.93201637097064
With 20 trees, the root mean squared error is 64.93 which is greater than 10 percent of the average petrol consumption i.e. 576.77. This may indicate, among other things, that we have not used enough estimators (trees).


In [10]:
# Change the n_estimator variable to 200 trees
#Train the model using scikit -learn
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=200, random_state=0)  
regressor.fit(X_train, y_train)  
y_pred = regressor.predict(X_test) 

print(y_pred,y_test)

[569.205 492.575 600.91  592.405 607.065 609.635 589.965 570.74  469.89
 509.815] [534 410 577 571 577 704 487 587 467 580]


In [11]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))  

Mean Absolute Error: 47.9825
Mean Squared Error: 3469.7007375000007
Root Mean Squared Error: 58.90416570583103


## <font color = "turquoise" size = 8 >Classification</font><br>
## Problem Definition
<p>
The task here is to predict whether a bank currency note is authentic or not based on four attributes i.e. variance of the image wavelet transformed image, skewness, entropy, and curtosis of the image.</p>
<a href = "https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view">Download the Dataset Here</a>

In [12]:
# The dataset can be downloaded from https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
dataset = pd.read_csv("bill_authentication.csv")  
dataset.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [47]:
#split the data into features and target
X = dataset.iloc[:, 0:4].values  
y = dataset.iloc[:, 4].values

#split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [48]:
dataset.iloc[:, 4].unique()

array([0., 1.])

In [49]:
from sklearn.preprocessing import StandardScaler # scale the data for a better fit

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)


In [95]:
from sklearn.ensemble import RandomForestClassifier # fit the model

regressor = RandomForestClassifier(n_estimators=20, random_state=0)  
regressor.fit(X_train,y_train.reshape(-1,1))  # the reshape allows the 1 column numpy array to be used in the model without errors


C:\Users\Gilgamesh\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [97]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score # test the quality of the model youve built


y_pred = regressor.predict(X_test) # The predictions from the model of the target from the features

confusion_df = pd.DataFrame(confusion_matrix(y_test,y_pred),
             columns=["Predicted Class " + str(class_name) for class_name in [0,1]],
             index = ["__Class " + str(class_name) for class_name in [0,1]])

print(confusion_df) # confusion matrix just shows the true predictions vs the false predictions
accuracy = accuracy_score(y_test,y_pred)
print("__The Accuracy level of this model is: %s " % (accuracy)) # prints the overall accuracy levels[all correct predictions div all data points]


           Predicted Class 0  Predicted Class 1
__Class 0                155                  2
__Class 1                  1                117
__The Accuracy level of this model is: 0.9890909090909091 


In [92]:
from sklearn.metrics import classification_report,roc_auc_score

print(classification_report(y_test,y_pred)) # shows the accuracy levels for all the classes, helps you compare small adjustments and their effects on overall predictavility

             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99       157
        1.0       0.98      0.99      0.99       118

avg / total       0.99      0.99      0.99       275



If we add one more dimension to our analysis and check the Area Under the Receiver-Operating Characteristic (AUROC) metric. Intuitively, AUROC represents the likelihood of your model distinguishing observations from two classes. In other words, if you randomly select one observation from each class, what’s the probability that your model will be able to “rank” them correctly?



In [93]:
roc_auc_score(y_test,y_pred) # use imblearn to improve accuracy, and recall as well as ROC

0.9893932851128144